name: anima
services:
  blender:
    container_name: anima-blender
    build: .
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
    stdin_open: true
    tty: true
    network_mode: host

networks:
  default:
    name: anima-network