name: Build DevContainer

on:
  push:
    paths:
      - '.devcontainer/**'
      - '.github/workflows/*devcontainer.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repository name
        run: echo "REPO_NAME_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push to registry
        uses: docker/build-push-action@v5
        with:
          context: .devcontainer
          push: true
          tags: |
            ghcr.io/${{ env.REPO_NAME_LOWER }}/devcontainer:${{ github.ref_name }}
            ghcr.io/${{ env.REPO_NAME_LOWER }}/devcontainer:latest
          cache-from: type=registry,ref=ghcr.io/${{ env.REPO_NAME_LOWER }}/devcontainer:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ env.REPO_NAME_LOWER }}/devcontainer:buildcache,mode=max
