name: Run Test Suite

env:
  PYTHON_VERSION: '3.11.9' # Should match version in pyproject.toml
  PROJECT_CONFIG: 'pyproject.toml'

on:
  push:
    branches: [ "**" ]  # Run on all branches

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }} 

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ env.PYTHON_VERSION }}-${{ hashFiles(env.PROJECT_CONFIG) }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ env.PYTHON_VERSION }}-
          ${{ runner.os }}-pip-

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Check for changes
      uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          config:
            - ${{ env.PROJECT_CONFIG }}

    - name: Install the anima package
      if: steps.changes.outputs.config == 'true'
      run: make install
      env:
        SKIP_BLENDER_DEPS: 1

    - name: Run tests
      run: make test