name: Run Test Suite

env:
  PYTHON_VERSION: '3.11.9' # Should match version in pyproject.toml

on:
  push:
    branches: [ "**" ]  # Run on all branches
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }} 

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Build the anima package
      run: make build

    - name: Run tests
      run: make test