name: Run Anima Test Suite

env:
  PYTHON_VERSION: '3.11.9' # Should match version in pyproject.toml

on:
  push:
    branches: [ "**" ]  # Run on all branches

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }} 

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml', 'src/**/*.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install the anima package
      run: make install

    - name: Run tests
      run: make test