name: Run Anima Test Suite

env:
  PYTHON_VERSION: '3.11.9' # Should match version in pyproject.toml

on:
  push:
    branches: [ "**" ]  # Run on all branches

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }} 

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Cache Python dependencies
      uses: actions/cache@v4
      id: cache-deps
      with:
        path: |
          ~/.cache/pip
          ${{ env.pythonLocation }}
        key: ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-

    - name: Install the anima package
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: make install

    - name: Run tests
      run: make test